from pathlib import Path


class SourceFile:
    path: Path
    watches: list[SourceFile]

    def __init__(self, path: str | Path, watches: list=[]) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def read(self) -> str: ...
    def write(self, data: str) -> None: ...
    def exists(self) -> bool: ...
    def was_modified(self) -> bool: ...
    def object_file_upto_date(self) -> bool: ...
    def has_suffix(self, suffix) -> bool: ...
    def to_object_filename(self) -> Path: ...
    @staticmethod
    def from_list(objects: list | tuple) -> list["SourceFile"]: ...
