name: python3 build.py --lint

# Run lint CI on changes to main branch, or any PR to main. Do not run CI on
# any other branch.
# run only if there are changes on files that are linted
on:
  push:
    branches:
      - main
    paths:
      - "./Car/**/*.[ch]pp"
      - "./examples/**/*.[ch]pp"

  pull_request:
    branches: 
      - main
    paths:
      - "./Car/**/*.[ch]pp"
      - "./examples/**/*.[ch]pp"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-format-lint
  cancel-in-progress: true

jobs:
  format-lint-code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3

      - name: Install deps
        run: python3 -m pip install clang-format

      - name: Check code Formatting and Linting
        run: python3 build.py --lint
